import AxeBuilder from '@axe-core/playwright'
import { expect, test } from '@playwright/test'

import { sample } from './helpers'

// INV-001 end to end, using the files generated by scripts/make_samples.py.
// These tests write to the running stack's database (uploads are idempotent: re-uploading
// the sample updates the same 17 invoices).

test.describe.configure({ mode: 'serial' })

test('INV_001_AC9 uploading the sample shows the summary', async ({ page }) => {
  await page.goto('/invoices/upload')
  await page.getByTestId('file-input').setInputFiles(sample('invoices-sample.xlsx'))
  // The selected file (the recent-uploads table below may list the same name).
  await expect(page.locator('p', { hasText: 'invoices-sample.xlsx' })).toBeVisible()

  await page.getByRole('button', { name: 'Upload invoices' }).click()

  const heading = page.getByRole('heading', { name: 'Upload complete' })
  await expect(heading).toBeVisible()
  await expect(heading).toBeFocused()
  await expect(page.getByText(/^17 rows read · /)).toBeVisible()
  await expect(page.getByRole('table', { name: 'Rows that need fixing' })).toHaveCount(0)
  await expect(page.getByRole('link', { name: 'View invoices' })).toBeVisible()
  await page.screenshot({ path: 'test-results/inv-001-upload-sample.png', fullPage: true })

  const results = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()
  expect(results.violations.filter((v) => v.impact === 'serious' || v.impact === 'critical')).toEqual([])
})

test('INV_001_AC4_AC6a the error sample reports each problem row', async ({ page }) => {
  await page.goto('/invoices/upload')
  await page.getByTestId('file-input').setInputFiles(sample('invoices-with-errors.xlsx'))
  await page.getByRole('button', { name: 'Upload invoices' }).click()

  await expect(page.getByRole('heading', { name: 'Upload complete' })).toBeVisible()
  await expect(page.getByText(/^8 rows read · .* · 1 replaced by a later row · 5 need fixing$/)).toBeVisible()

  const table = page.getByRole('table', { name: 'Rows that need fixing' })
  await expect(table.getByRole('row')).toHaveCount(6) // header + 5
  await expect(table).toContainText('Customer Name is missing.')
  await expect(table).toContainText('Due Date')
  await expect(table).toContainText('Amount must be greater than zero.')
  await expect(table).toContainText("Date Raised '31/13/2026' is not a valid date.")
  await expect(table).toContainText('Amount can have at most 2 decimal places.')

  await page.getByText('Rows replaced by a later row (1)').click()
  await expect(page.getByText('Row 8 replaced row 2 (INV-2701)')).toBeVisible()
  await page.screenshot({ path: 'test-results/inv-001-upload-errors.png', fullPage: true })
})

test('INV_001_AC8 recent uploads lists the latest upload first', async ({ page }) => {
  await page.goto('/invoices/upload')

  const table = page.getByRole('table', { name: 'Recent invoice uploads' })
  await expect(table).toBeVisible()
  await expect(table.getByRole('row').nth(1)).toContainText('invoices-with-errors.xlsx')
})

test('INV_001_AC1 wrong file types are refused before upload', async ({ page }) => {
  await page.goto('/invoices/upload')
  await page.getByTestId('file-input').setInputFiles({
    name: 'invoices.csv',
    mimeType: 'text/csv',
    buffer: Buffer.from('Invoice Number,Customer Name\n'),
  })

  await expect(page.getByRole('alert')).toHaveText(
    "This file type isn't supported. Please choose an Excel file (.xlsx).",
  )
  await expect(page.getByRole('button', { name: 'Upload invoices' })).toHaveCount(0)
})

test('INV_001_AC1 the whole upload works with the keyboard alone', async ({ page }) => {
  await page.goto('/invoices/upload')

  const chooser = page.waitForEvent('filechooser')
  await page.getByRole('button', { name: 'Choose file' }).focus()
  await page.keyboard.press('Enter')
  await (await chooser).setFiles(sample('invoices-sample.xlsx'))

  const uploadButton = page.getByRole('button', { name: 'Upload invoices' })
  await uploadButton.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('heading', { name: 'Upload complete' })).toBeFocused()
})

test('INV_001_AC11 the template downloads', async ({ page }) => {
  await page.goto('/invoices/upload')

  const download = page.waitForEvent('download')
  await page.getByRole('link', { name: 'Download template' }).click()

  expect((await download).suggestedFilename()).toBe('invoice-template.xlsx')
})
